acai/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='acai'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='detalhe'),#mudancas aqui"
	url(r'^oferta$', views.oferta, name='oferta'),
	url(r'^comboa$', views.comboa, name='comboa'),
	url(r'^combob$', views.combob, name='combob'),
	url(r'^bebidas$', views.bebidas, name='bebidas'),
	url(r'^cupons$', views.cupons, name='cupons'),
	]

botucatu/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^acaidavital/', include('acai.urls', namespace='acai')),
    url(r'^sandubaslanches/', include('sandubas.urls', namespace='sandubas')),
    url(r'^queromais/', include('queromais.urls', namespace='queromais')),
    url(r'^divino/', include('divino.urls', namespace='divino'))
]

core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^vital/$', views.vital, name='vital'),
	url(r'^bairro/$', views.bairro, name='bairro'),
	url(r'^centro/$', views.centro, name='centro'),
	url(r'^domlucio/$', views.domlucio, name='domlucio'),
	url(r'^facaparte/$', views.facaparte, name='parte'),
]

queromais/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='queromais'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='detalhe'),
	url(r'^cardapio$', views.cardapio, name='cardapio'),
	url(r'^novidades$', views.novidades, name='novidades'),
	url(r'^cupons$', views.cupons, name='cupons'),
	]

queromais/models.py
# -*- coding: utf 8 -*-
from django.db import models
from django.utils import timezone
from cloudinary.models import CloudinaryField

class Queromais(models.Model):
	TIPOS = (
		('CARD', 'Cardápio'),
		('NOVID', 'Novidades'),
		('CUPONS', 'Cupons'),
		('INI', 'Inicial')
	)

	tipos = models.CharField(max_length=6, choices=TIPOS, null=False)
	titulo = models.CharField(max_length=100, null=False, blank=False)
	apresentacao = models.TextField()
	imagem = CloudinaryField('imagem', null=False, blank=False)
	validade = models.DateField(null=True, blank=True)#testar a validade assim
	datapublicacao = models.DateField(null=False, blank=False)

	def publish(self):
		self.publish_date = timezone.now()
		self.save()

	def __str__(self):
		return self.titulo

	def get_absolute_url(self):
		#return reverse("detalhe", kwargs={"pk": self.pk})
		return "post/%s" %(self.pk)

queromais/views.py
# -*- coding: utf 8 -*-
import datetime
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from datetime import timedelta
from .models import Queromais

def index(request):
	queromais = Queromais.objects.filter(tipos='INI', datapublicacao__lte=timezone.now()).order_by('-datapublicacao')
	return render(request, 'queromais/index.html', {'queromais': queromais})	

def post_detail(request, pk):
    post = get_object_or_404(Queromais, pk=pk)
    Queromais.objects.get(pk=pk)
    return render(request, 'queromais/post_detail.html', {'post': post})

def cardapio(request):
	queromais = Queromais.objects.filter(tipos='CARD')
	return render(request, 'queromais/index.html', {'queromais': queromais})

def novidades(request):
	queromais = Queromais.objects.filter(tipos='NOVID')
	return render(request, 'queromais/index.html', {'queromais': queromais})
	
def cupons(request):
	tickets = Queromais.objects.filter(tipos='CUPONS')
	return render(request, 'queromais/index.html', {'tickets': tickets})

#modificacao

queromais/templates/queromais/base2.html
<!DOCTYPE html>
{% load cloudinary %}
{% load staticfiles %}
<html lang="pt">
	<head>
		<title>Cadê o Saci?</title>
		<meta property="fb:app_id" content="174138446539993">
		<meta property="fb:admins" content="100002421374214">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet">
		<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
		<link rel="stylesheet" href="/static/css/botucatu.css">
		<meta property="og:type" content="website">
		<meta property="og:title" content="{{ post.titulo }}">
		<meta property="og:description" content="{{ post.apresentacao }}" >
		<meta property="og:image" content="{% cloudinary_url post.imagem %}" > 
		<meta property="og:url" content="{{ request.build_absolute_uri }}">
		<script>
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
			ga('create', 'UA-113877603-1', 'auto');
			ga('send', 'pageview');
		</script>
	</head>
	<header class="opener">
		<div class="logo4">
			<img src="{% static 'images/queromais2.png' %}" alt="logo"/>
		</div>
		<title>Sejam bem vindos, e que possamos ajudar-te</title> 
		<div class="texto">
			<center><br><h1 style="text_align:center;">O Saci encontrou!</h1><br><br></center><!-- Pensar em uma animação bacana com css a ser inserida aqui -->
			<h1 style="text_align:center;">Lanches Quero +!</h1></center>
		<div class='btns2'>
			<table>
				<tr>
					<td><h2><a href="{% url 'queromais:cardapio' %}"><button class='btn1'>Cardápio</button></a></h2></td>
					<td><h2><a href="{% url 'queromais:novidades' %}"><button class='btn2'>Novidades</button></a></h2></td>
					<td><h2><a href="{% url 'queromais:cupons' %}"><button class='btn2'>Cupons</button></a></h2></td>
				</tr>
			</table>
		</div>
	</header>
	<body>
<!-- Facebook -->
		<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.12&appId=174138446539993&autoLogAppEvents=1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!-- Facebook -->
		{% block content %}
		{% endblock %}	
	</body>
		<div class='rodape2'>
			<footer>
				<center><h2><a href="{% url 'core:index' %}"><img src="{% static 'css/home.png' %}" class='voltar'><br><br><br>&nbsp;</img></a></h2></center>
			</footer>
		</div>
		</div>
	

queromais/templates/queromais/index.html
{% extends 'queromais/base2.html' %}
{% load cloudinary %}
{% load staticfiles %}
{% block content %}

	{% for quero in queromais %}
	            <div class= 'ini'>	            	
	                <center><h3><p>Publicado em:{{ quero.datapublicacao }}</p></h3><center>
	                <center><h1><bold><a href="{{ quero.get_absolute_url }}">{{ quero.titulo }}</a></bold></h1></center>
	                <center><img>{% cloudinary quero.imagem %}</center>
	                <center><p><h2>{{ quero.apresentacao }}</h2></p></center>
	                <br>
	                <br>
	            </div>
	{% endfor %}
	{% for ticket in tickets %}
		<center><div class= 'coupon'>
					<div class= 'container'>
						<img src="{% static 'images/logo3.png' %}" alt="logo"/>
					</div>
	                <img>{% cloudinary ticket.imagem %}</img>
	                <div class="container1">
	                	<center><h1><bold><a href="{{ ticket.get_absolute_url }}">{{ ticket.titulo }}</a></bold></h1></center>
	                </div>
	                <center><div class= 'container2'>
	                	<p><h2><br>{{ ticket.apresentacao }}<br><br></h2></p>
	                	<div class='expire'>
	                		<p><h3><b>Valido até:{{ ticket.validade }}</b></h3></p>
	                	</div>
	                </div></center>	                
	   </center></div>
	   <br>
	{% endfor %}
	<br>
    <br>
    <div class="mapa">
    	<center><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14703.596239818073!2d-48.423506499999995!3d-22.880186899999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94c6df8de370ad55%3A0x3fd4a9b7e45ab703!2sDISK+LANCHE+QUERO%2B!5e0!3m2!1spt-BR!2sbr!4v1521944555916" width="600" height="450" frameborder="5" style="border:2" allowfullscreen></iframe></center>
    <br>
{% endblock %}

queromais/templates/queromais/post_detail.html
{% extends 'queromais/base2.html' %}
{% load cloudinary %}
{% block content %}
<!-- Compartilhar -->
<div class="fb-share-button" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-size="large" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Compartilhe</a></div>
<!-- Curtir -->
<div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-size="large" data-show-faces="false" data-share="false"></div>
    <div class="post">
        {% if post.datapublicacao %}
            <div class="date">
                <center><h3><b>{{ post.datapublicacao }}</b></h3></center>
            </div>
        {% endif %}
        <center><p><h1>{{ post.titulo }}</h1></p></center>
        <center><img>{% cloudinary post.imagem %}</img></center>
        <center><p><h2>{{ post.apresentacao|linebreaksbr }}</h2></p></center>
    </div>
    <footer>
        <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="2"></div>
    </footer>
{% endblock %}