acai/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='acai'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='detalhe'),#mudancas aqui"
	url(r'^oferta$', views.oferta, name='oferta'),
	url(r'^comboa$', views.comboa, name='comboa'),
	url(r'^combob$', views.combob, name='combob'),
	url(r'^bebidas$', views.bebidas, name='bebidas'),
	url(r'^cupons$', views.cupons, name='cupons'),
	]

botucatu/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^acaidavital/', include('acai.urls', namespace='acai')),
    url(r'^sandubaslanches/', include('sandubas.urls', namespace='sandubas')),
    url(r'^queromais/', include('queromais.urls', namespace='queromais')),
    url(r'^divino/', include('divino.urls', namespace='divino'))
]

core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^vital/$', views.vital, name='vital'),
	url(r'^bairro/$', views.bairro, name='bairro'),
	url(r'^centro/$', views.centro, name='centro'),
	url(r'^domlucio/$', views.domlucio, name='domlucio'),
	url(r'^facaparte/$', views.facaparte, name='parte'),
]

divino/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='divino'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='detalhe'),#mudancas aqui"
	url(r'^cardapio$', views.cardapio, name='cardapio'),
	url(r'^combos$', views.combos, name='combos'),
	url(r'^cupons$', views.cupons, name='cupons'),
	]

queromais/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='queromais'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='detalhe'),
	url(r'^cardapio$', views.cardapio, name='cardapio'),
	url(r'^novidades$', views.novidades, name='novidades'),
	url(r'^cupons$', views.cupons, name='cupons'),
	]

sandubas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='sandubas'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='detalhe'),#mudancas aqui"
	url(r'^hotdog&lanches$', views.hotdog, name='hotdog'),
	url(r'^barca$', views.barca, name='barca'),
	url(r'^pratos$', views.pratos, name='pratos'),
	url(r'^porcoes$', views.porcoes, name='porcoes'),
	url(r'^cupons$', views.cupons, name='cupons'),
	]

core/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.utils import timezone


class Promocao(models.Model):
	nome = models.CharField(max_length=200, null=False, blank=False)
	apresentacao = models.TextField(null=False, blank=False)
	foto = CloudinaryField('foto', null=True, blank=True)
	postado = models.DateTimeField(
            default=timezone.now)
	encerramento = models.DateTimeField(
            blank=True, null=True)

	def publish(self):
		self.postado = timezone.now()
		self.save()

	def __str__(self):
		return self.nome

core/views.py
import datetime
from django.shortcuts import render
from django.utils import timezone
from datetime import timedelta
from .models import Promocao
from acai.models import Acai
from sandubas.models import Sandubas
from queromais.models import Queromais
from divino.models import Divino

def index(request):
	#no posts, posso fazer no models um campo para data limite de exibicao, desta forma crio aqui no views a condicao para a exibicao do mesmo.
	posts = Promocao.objects.filter(encerramento__gt=timezone.now()).order_by('-encerramento')
	acais = Acai.objects.filter(datapublicacao__gt=timezone.now().date() - timedelta(days=30)).order_by('-datapublicacao')[0:3]
	sandubas = Sandubas.objects.filter(datapublicacao__gt=timezone.now().date() - timedelta(days=30)).order_by('-datapublicacao')[0:3]
	queromais = Queromais.objects.filter(datapublicacao__gt=timezone.now().date() - timedelta(days=30)).order_by('-datapublicacao')[0:3]
	divinos = Divino.objects.filter(datapublicacao__gt=timezone.now().date() - timedelta(days=30)).order_by('-datapublicacao')[0:3]
	return render(request, 'core/index.html', {'posts': posts, 'acais': acais, 'sandubas': sandubas, 'queromais': queromais, 'divinos': divinos})

def vital(request):
	return render(request, 'core/vital.html', {})

def bairro(request):
	return render(request, 'core/bairro.html', {})

def centro(request):
	return render(request, 'core/centro.html', {})

def domlucio(request):
	return render(request, 'core/domlucio.html', {})

def facaparte(request):
	return render(request, 'core/facaparte.html', {})

core/templates/core/bairro.html
{% extends 'core/base.html' %}
{% load cloudinary %}
{% load staticfiles %}
{% block content %}
	<div class="imagem">
		<center><img src="{% static 'images/bairro.png' %}" alt="Bairro Nova Botucatu!"></center>
	</div>
	<center><p><h1>Lojas disponíveis:<br>Bairro</h1></p></center>
	<div class='tabela'>
		<table border="5">
			<center>
				<tr>
					<td><b><h1>Nome da empresa</h1></b></td>
					<td><b><h1>Um pouco sobre</h1></b></td>
					<td><b><h1>Link</h1></b></td> 
				</tr>
				<tr>
					<td><h2>Divino Restaurante</h2></td>
					<td><h2>Breve descrição da loja!</h2></td>
					<td><a href="{% url 'divino:divino' %}"><img src="{% static 'images/divino.ico' %}" alt="divino!"></td>
				</tr>
			</center>
		</table>
	</div>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
{% load cloudinary %}
{% load staticfiles %}
<html lang="pt">
	<head>
		<title>Cadê o Saci?</title>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
		<meta name="author" content="Visus">
		<meta name="description" content="Cadê o Saci? - Um só lugar, todos os comércios de Botucatu!">
		<meta name="keywords" content="botucatu, comércios, cadê o saci">
		<meta name="robots" content="index,follow">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="https://fonts.googleapis.com/css?family=Ubuntu+Condensed" rel="stylesheet">
		<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
		<link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
		<link rel="stylesheet" href="/static/css/botucatu.css">
		<script>
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
			ga('create', 'UA-102290379-2', 'auto');
			ga('send', 'pageview');
		</script>
	</head>
	<header class="opener">
		<div class="logo">
			<img src="{% static 'images/logo2.png' %}" alt="logo"/>
		</div>
		<div class="texto">
			<center><br><h1 style="text_align:center;">Cadê o Saci?</h1><br></center><!-- Pensar em uma animação bacana com css a ser inserida aqui -->
			<h2 style="text_align:center;">Não sabemos onde estão os melhores comércios de Botucatu,<br></h2></center><p><center><h2 style="text_align:center;"> mas o Saci nos ajuda a encontrar!</h2></center></p>
		<div class='btns'>
			<table>
				<tr>
					<td><h2><a href="{% url 'core:vital' %}"><button class='btn1'>Av.Vital Brasil</button></a></h2></td>
					<td><h2><a href="{% url 'core:bairro' %}"><button class='btn2'>Bairro. Bairro</button></a></h2></td>
					<td><h2><a href="{% url 'core:centro' %}"><button class='btn3'>Centro</button></h2></a></td>
					<td><h2><a href="{% url 'core:domlucio' %}"><button class='btn4'>Av. Dom Lucio</button></h2></a></td>
				</tr>
			</table>
	</header>
	<body>
		{% block content %}
		{% endblock %}	
	</body>
	<br>
	<br>
	<br>
	<br>
	<br>
	<div class="rodape">
		<footer>
			<center><h2><a href="{% url 'core:parte' %}" target="_blank"><button class='vcaqui'><br>Como funciona?<br><br></button></a></h2></center><!-- Fixar o footer na parte mais abaixo da tela no css, pra melhorar a visibilidade no celuçar -->
		</footer>
	</div>
</html>

core/templates/core/centro.html
{% extends 'core/base.html' %}
{% load cloudinary %}
{% load staticfiles %}
{% block content %}
	<div class="imagem">
		<center><img src="{% static 'images/centro.png' %}" alt="Centro de Botucatu!"></center>
	</div>
	<center><p><h1>Lojas disponíveis:<br>Centro</h1></p></center>
	<div class='tabela'>
		<table border="5">
			<center>
				<tr>
					<td><b><h1>Nome da empresa</h1></b></td>
					<td><b><h1>Um pouco sobre</h1></b></td>
					<td><b><h1>Link</h1></b></td> 
				</tr>
				<tr>
					<td><h2>Lanches Quero +</h2></td>
					<td><h2>Breve descrição da loja!</h2></td>
					<td><a href="{% url 'queromais:queromais' %}"><img src="{% static 'images/queromais.ico' %}" alt="queromais!"></td>
				</tr>
			</center>
		</table>
	</div>	
{% endblock %}
	

core/templates/core/domlucio.html
{% extends 'core/base.html' %}
{% load cloudinary %}
{% load staticfiles %}
{% block content %}
	<div class='imagem'>
		<center><img src="{% static 'images/domlucio.png' %}" alt="Av. DomLucio!"></center>
	</div>
	<center><p><h1>Lojas disponíveis:<br>Av. Dom Lucio</h1></p></center>
	<div class='tabela'>
		<table border="5">
			<center>
				<tr>
					<td><b><h1>Nome da empresa</h1></b></td>
					<td><b><h1>Um pouco sobre</h1></b></td>
					<td><b><h1>Link</h1></b></td> 
				</tr>
				<tr>
					
				</tr>
		



{% endblock %}

core/templates/core/facaparte.html
{% extends 'core/base.html' %}
{% load cloudinary %}
{% load staticfiles %}
{% block content %}
	<div class="cliente">
		<p><h2><i>Para quem o acessa:</i></h2><h3>O objetivo deste projeto é unir em um só lugar, informações referentes aos comércios de Botucatu, informações estas que são inseridas pelos próprios donos dos comércios. Desta forma, tentamos expor para você, os comércios em função de suas localizações. Assim, de uma maneira divertida, usando a nossa própria cultura e costumes locais, dividimos no site da maneira como Botucatu é popularmente dividida em função de sua localização.</h3></p>
		<p><h3>E por último, mas não menos importante, estamos aqui não como uma empresa que visa lucros, mas como uma ideia proposta a fim de resolver um problema. Logo, sua opinião em como estamos trabalhando é deveras importante, estamos abertos à sugestões, críticas e afins. Nos ajude a encontrar o Saci de uma forma melhor ^^.</h3></p> 
	<div class="comercio">
		<p><h2><i>E para os comércios:</i></h2><h3>Aqui oferecemos uma forma de divulgação de seu comércio. Diferente de um site simples, você terá autonomia para publicar suas promoções, assim como divulgá-las. Como estamos também na principal rede social mundial (Facebook, é claaaaro) há a possibilidade de usuários curtirem, publicarem e comentarem suas publicações. Desta forma, têm-se diretamente um feedback de seus produtos, assim como uma maneira de fazer promoções alguns fast foods, como Mac Donalds e Burger King usam cupons para dar discontos em seus produtos, aqui você pode facilmente fazer o mesmo.</h3></p>
		<p><h2><i>Valor:</i></h2><h3>Como o projeto tem um "visual elástico", ele se adequa bem a qualquer resolução de tela, logo, pode ser facilmente visualizado em dispositivo smartphone como também em computador (no entanto, qualquer problema quanto a visualização, você pode nos enviar um email informando sobre o mesmo, tentaremos resolver o quão breve for possível), o que é um ponto importante, visto que hoje estamos constantemente conectados. A presença do projeto no facebook (isto mesmo, não a empresa, mas sim a plataforma em si) torna fácil a integração das publicações no site com o facebook.</h3></p>
		<p><h3>Você não precisa ter nenhum conhecimento de marketing ou de programação, construímos sua página (o que chamamos de aplicativo) em função de suas escolhas, assim como também lhe orientamos como interpretar as leituras do google analytics. Lembre-se sempre que, a sua opinião é importante para nós, então qualquer ponto que você não tenha entendido, ou qualquer crítica, agradecemos imensamente o feedback de sua parte. A sua participação na busca pelo Saci torna este projeto melhor a cada nova ideia, nova crítica.</h3></p>   
		<p><h2><i>Objetivo:</i></h2><h3>Botucatu possui uma distância muito grande entre suas regiões. Por exemplo, ir verificar preços ou mesmo opções de comida no Bairro ou no Centro, é uma tarefa um pouco complicada, se esta pessoa residir na Vital. Mesmo não havendo de fato um bairro chamado Bairro, Centro ou Vital, é a maneira como dividimos a cidade, e estes pontos são distantes entre si. Então o principal objetivo deste projeto é fazer com que essa pessoa consiga se informar sobre as opções nos demais bairros, assim como também levar aos estudantes de escolas, das universidades, as opções existentes em função da localização da mesma. Com a ajuda do Saci, podemos sim "encurtar" a distância entre os bairros. Novamente salientamos, se de alguma forma não estamos atingindo nossos objetivos de forma satisfatória, por favor nos informe, nos ajude a mudar.</h3></p>
		<p><h2><i>Instruções:</i></h2><h3>Para se criar um site necessita-se de algum conhecimento de web design, tornar este site dinâmico necessita de programação, e ser encontrado pelo google, e ter uma participação dinâmica no facebook necessita de marketing.</h3></p>
		<p><h3>Então deixa com a gente, é nossa função fazer o trabalho pesado. Você só deve se preocupar em atualizar seus produtos assim como publicar no site (e consequentemente no facebook) o seu produto. Tudo o que você deve fazer é enviar-nos um email, veja abaixo, para lhe atendermos. Assim poderemos construir a sua página dentro do projeto, portanto nos envie um email informando onde o seu comércio se localiza, o que é comercializado, para que podemos inicar algum esboço e termos juntos ideias para o seu comércio em específico.
		Mas se você não quiser ter uma parte fixa própria no projeto, e apenas publicar aqui eventualmente, este também é o lugar certo para isto. Sim, nós tentamos pensar em tudo!
		<p><h2><i>Contato:</i></h2><h3>Envie-nos um email para críticas, sugestões, reclamações, angustias...Enfim, não fazemos spam, então responderemos pessoalmente a cada email nos enviado. Todos serão lidos e defidamente respondidos. Nossos sinceros agradecimentos por ter lido até aqui, e que consigámos encontrar o Saci.</h3></p>
		<p><h3><i>Enfim o email:</i></h3><br><h2 id="contato">contato@cadeosaci.com.br</h2><h3>Sem diferenciar maiúsculas de minúsculas.</h3>  
	</div>



{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load cloudinary %}
{% load staticfiles %}
{% block content %}

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script>
		$(function () {
    		var parent = $("#shuffle");
    		var divs = parent.children();
    		while (divs.length) {
        		parent.append(divs.splice(Math.floor(Math.random() * divs.length), 1)[0]);
    		}
		});
		</script>

	<div class='ini'>
		{% for post in posts %}
			<br>
	        <center><h3><p>Publicado em:{{ post.postado }}</p></h3><center>
	        <center><h2>{{ post.nome }}</h2></center>
	        <center><img>{% cloudinary post.foto %}</center>
	        <center><p><h2>{{ post.apresentacao }}</h2></p></center>
	        <br>
	    {% endfor %}
	</div>	

<!-- Toda nova empresa deve ser jogada aqui, dentro de shuffle, para poder ser exibida na tela inicial -->
	<div id="shuffle">
				
		<div class='ini2'>
			<center><h1><i><br><a href="{% url 'acai:acai' %}">Açaí da Vital - Vital</a><br></i></h1></center>
				{% for acai in acais %}
				    
				        <br>
				        <center><h3><p>Publicado em:{{ acai.datapublicacao }}</p></h3><center>
				        <center><h2>{{ acai.titulo }}</h2></center>
				        <center><img>{% cloudinary acai.imagem %}</center>
				        <center><p><h2>{{ acai.apresentacao }}</h2></p></center>
				        <br>
				            
				{% endfor %}
				<br>
				<br>
		</div>

		<div class='ini'>
			<center><h1><i><br><a href="{% url 'sandubas:sandubas' %}">Sandubas Lanches - Vital</a><br></i></h1></center>
				{% for sanduba in sandubas %}
				    
				        <br>
				        <center><h3><p>Publicado em:{{ sanduba.datapublicacao }}</p></h3><center>
				        <center><h2>{{ sanduba.titulo }}</h2></center>
				        <center><img>{% cloudinary sanduba.imagem %}</center>
				        <center><p><h2>{{ sanduba.apresentacao }}</h2></p></center>
				        <br>
				            
				{% endfor %}
				<br>
				<br>
		</div>

		<div class='ini2'>
			<center><h1><i><br><a href="{% url 'queromais:queromais' %}">Lanches Quero Mais - Centro</a><br></i></h1></center>
				{% for quero in queromais %}
				    
				        <br>
				        <center><h3><p>Publicado em:{{ quero.datapublicacao }}</p></h3><center>
				        <center><h2>{{ quero.titulo }}</h2></center>
				        <center><img>{% cloudinary quero.imagem %}</center>
				        <center><p><h2>{{ quero.apresentacao }}</h2></p></center>
				        <br>
				            
				{% endfor %}
				<br>
				<br>
		</div>

		<div class='ini'>
			<center><h1><i><br><a href="{% url 'divino:divino' %}">Divino Restaurante - Bairro</a><br></i></h1></center>
				{% for divino in divinos %}
				    
				        <br>
				        <center><h3><p>Publicado em:{{ divino.datapublicacao }}</p></h3><center>
				        <center><h2>{{ divino.titulo }}</h2></center>
				        <center><img>{% cloudinary divino.imagem %}</center>
				        <center><p><h2>{{ divino.apresentacao }}</h2></p></center>
				        <br>
				            
				{% endfor %}
				<br>
				<br>
		</div>


	</div>
{% endblock %}

core/templates/core/vital.html
{% extends 'core/base.html' %}
{% load cloudinary %}
{% load staticfiles %}
{% block content %}
	<div class='imagem'>
		<center><img src="{% static 'images/vital.png' %}" alt="Av. Vital Brasil!"></center>
	</div>
	<center><p><h1>Lojas disponíveis:<br>Vital Brasil</h1></p></center>
	<div class='tabela'>
		<table border="5">
			<center>
				<tr>
					<td><b><h1>Nome da empresa</h1></b></td>
					<td><b><h1>Um pouco sobre</h1></b></td>
					<td><b><h1>Link</h1></b></td> 
				</tr>
			
				<tr>
					<td><h2>Sandubas Lanches</h2></td>
					<td><h2>Breve descrição da loja!</h2></td>
					<td><a href="{% url 'sandubas:sandubas' %}"><img src="{% static 'images/sandubas.ico' %}" alt="sandubas!"></td>
				</tr>

				<tr>
					<td><h2>Açaí da Vital</td>
					<td><h2>Editar com Amor e Carinho</td>
					<td><a href="{% url 'acai:acai' %}"><img src="{% static 'images/acai.ico' %}" alt="Açaí da Vital"></td>
				</tr> 
			</center>
		</table>
	</div>
{% endblock %}