acai/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='acai'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='detalhe'),#mudancas aqui"
	url(r'^oferta$', views.oferta, name='oferta'),
	url(r'^comboa$', views.comboa, name='comboa'),
	url(r'^combob$', views.combob, name='combob'),
	url(r'^bebidas$', views.bebidas, name='bebidas'),
	url(r'^cupons$', views.cupons, name='cupons'),
	]

botucatu/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^acaidavital/', include('acai.urls', namespace='acai')),
    url(r'^sandubaslanches/', include('sandubas.urls', namespace='sandubas')),
    url(r'^queromais/', include('queromais.urls', namespace='queromais')),
    url(r'^divino/', include('divino.urls', namespace='divino'))
]

core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^vital/$', views.vital, name='vital'),
	url(r'^bairro/$', views.bairro, name='bairro'),
	url(r'^centro/$', views.centro, name='centro'),
	url(r'^domlucio/$', views.domlucio, name='domlucio'),
	url(r'^facaparte/$', views.facaparte, name='parte'),
]

sandubas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='sandubas'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='detalhe'),#mudancas aqui"
	url(r'^hotdog&lanches$', views.hotdog, name='hotdog'),
	url(r'^barca$', views.barca, name='barca'),
	url(r'^pratos$', views.pratos, name='pratos'),
	url(r'^porcoes$', views.porcoes, name='porcoes'),
	url(r'^cupons$', views.cupons, name='cupons'),
	]

sandubas/models.py
# -*- coding: utf 8 -*-
from django.db import models
from django.utils import timezone
from cloudinary.models import CloudinaryField

class Sandubas(models.Model):
	TIPOS = (
		('HOTDOG', 'Lanches e Hot-dog'),
		('BARCA', 'Barca'),
		('PFE', 'Pratos Executivos'),
		('PORC', 'Porções e Bebidas'),
		('CUPONS', 'Cupons'),
		('INI', 'Inicial')
	)

	tipos = models.CharField(max_length=6, choices=TIPOS, null=False)
	titulo = models.CharField(max_length=100, null=False, blank=False)
	apresentacao = models.TextField()
	imagem = CloudinaryField('imagem', null=False, blank=False)
	validade = models.DateField(null=True, blank=True)#testar a validade assim
	datapublicacao = models.DateField(null=False, blank=False)

	def publish(self):
		self.publish_date = timezone.now()
		self.save()

	def __str__(self):
		return self.titulo

	def get_absolute_url(self):
		#return reverse("detalhe", kwargs={"pk": self.pk})
		return "post/%s" %(self.pk)

sandubas/views.py
# -*- coding: utf 8 -*-
import datetime
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from datetime import timedelta
from .models import Sandubas

def index(request):
	sandubas = Sandubas.objects.filter(tipos='INI', datapublicacao__lte=timezone.now()).order_by('-datapublicacao')
	return render(request, 'sandubas/index.html', {'sandubas': sandubas})	

def post_detail(request, pk):
    post = get_object_or_404(Sandubas, pk=pk)
    Sandubas.objects.get(pk=pk)
    return render(request, 'sandubas/post_detail.html', {'post': post})

def hotdog(request):
	sandubas = Sandubas.objects.filter(tipos='HOTDOG')
	return render(request, 'sandubas/index.html', {'sandubas': sandubas})

def barca(request):
	sandubas = Sandubas.objects.filter(tipos='BARCA')
	return render(request, 'sandubas/index.html', {'sandubas': sandubas})
	
def pratos(request):
	sandubas = Sandubas.objects.filter(tipos='PFE')
	return render(request, 'sandubas/index.html', {'sandubas': sandubas})

def porcoes(request):
	sandubas = Sandubas.objects.filter(tipos='PORC')
	return render(request, 'sandubas/index.html', {'sandubas': sandubas})

def cupons(request):
	tickets = Sandubas.objects.filter(tipos='CUPONS')
	return render(request, 'sandubas/index.html', {'tickets': tickets})

#modificacao

sandubas/templates/sandubas/base2.html
<!DOCTYPE html>
{% load cloudinary %}
{% load staticfiles %}
<html lang="pt">
	<head>
		<title>Cadê o Saci?</title>
		<meta property="fb:app_id" content="174138446539993">
		<meta property="fb:admins" content="100002421374214">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet">
		<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
		<link rel="stylesheet" href="/static/css/botucatu.css">
		<meta property="og:type" content="website">
		<meta property="og:title" content="{{ post.titulo }}">
		<meta property="og:description" content="{{ post.apresentacao }}" >
		<meta property="og:image" content="{% cloudinary_url post.imagem %}" > 
		<meta property="og:url" content="{{ request.build_absolute_uri }}">
		<script>
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
			ga('create', 'UA-102290379-2', 'auto');
			ga('send', 'pageview');
		</script>
	</head>
	<header class="opener">
		<div class="logo">
			<img src="{% static 'images/sandubas.png' %}" alt="logo"/>
		</div>
		<title>Sejam bem vindos, e que possamos ajudar-te</title> 
		<div class="texto">
			<center><br><h1 style="text_align:center;">Cadê o Saci?</h1><br></center><!-- Pensar em uma animação bacana com css a ser inserida aqui -->
			<h2 style="text_align:center;">O Saci encontrou:<br></h2></center><p><center><h2 style="text_align:center;"> Sandubas Lanches!</h2></center></p>
		<div class='btns'>
			<table>
				<tr>
					<td><h2><a href="{% url 'sandubas:hotdog' %}"><button class='btn1'>Lanches<br> Hot-dog</button></a></h2></td>
					<td><h2><a href="{% url 'sandubas:barca' %}"><button class='btn2'>Barca</button></a></h2></td>
					<td><h2><a href="{% url 'sandubas:pratos' %}"><button class='btn3'>Pratos<br>Executivos</button></h2></a></td>
					<td><h2><a href="{% url 'sandubas:porcoes' %}"><button class='btn4'>Porções<br> Bebidas</button></h2></a></td>
					<td><h2><a href="{% url 'sandubas:cupons' %}"><button class='btn4'>Cupons</button></h2></a></td>
				</tr>
			</table>
		</div>
	</header>
	<body>
	<!-- Facebook -->
		<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.12&appId=174138446539993&autoLogAppEvents=1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!-- Facebook -->
		{% block content %}
		{% endblock %}	
	</body>
		<div class='rodape2'>
			<footer>
				<center><h2><a href="{% url 'core:index' %}"><img src="{% static 'css/home.png' %}" class='voltar'><br><br><br>&nbsp;</img></a></h2></center>
			</footer>
		</div>
		</div>
	

sandubas/templates/sandubas/index.html
{% extends 'sandubas/base2.html' %}
{% load cloudinary %}
{% load staticfiles %}
{% block content %}

	{% for sanduba in sandubas %}
	            <div class= 'ini'>	            	
	                <center><h3><p>Publicado em:{{ sanduba.datapublicacao }}</p></h3><center>
	                <center><h1><bold><a href="{{ sanduba.get_absolute_url }}">{{ sanduba.titulo }}</a></bold></h1></center>
	                <center><img>{% cloudinary sanduba.imagem %}</center>
	                <center><p><h2>{{ sanduba.apresentacao }}</h2></p></center>
	                <br>
	                <br>
	            </div>
	{% endfor %}
	{% for ticket in tickets %}
		<center><div class= 'coupon'>
					<div class= 'container'>
						<img src="{% static 'images/logo3.png' %}" alt="logo"/>
					</div>
	                <img>{% cloudinary ticket.imagem %}</img>
	                <div class="container1">
	                	<center><h1><bold><a href="{{ ticket.get_absolute_url }}">{{ ticket.titulo }}</a></bold></h1></center>
	                </div>
	                <center><div class= 'container2'>
	                	<p><h2><br>{{ ticket.apresentacao }}<br><br></h2></p>
	                	<div class='expire'>
	                		<p><h3><b>Valido até:{{ ticket.validade }}</b></h3></p>
	                	</div>
	                </div></center>	                
	   </center></div>
	   <br>
	{% endfor %}
	<br>
    <br>
    <div class="mapa">
    	<center><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3675.801121343228!2d-48.45492904993467!3d-22.883803984949967!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94c6df63c6b7adff%3A0x8d60d158cf810d79!2sSandubas+Lanches!5e0!3m2!1spt-BR!2sbr!4v1522805477607" width="600" height="450" frameborder="5" style="border:2" allowfullscreen></iframe></center>
    <br>
{% endblock %}

sandubas/templates/sandubas/post_detail.html
{% extends 'sandubas/base2.html' %}
{% load cloudinary %}
{% block content %}
<!-- Compartilhar -->
<div class="fb-share-button" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-size="large" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Compartilhe</a></div>
<!-- Curtir -->
<div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-size="large" data-show-faces="false" data-share="false"></div>
    <div class="post">
        {% if post.datapublicacao %}
            <div class="date">
                <center><h3><b>{{ post.datapublicacao }}</b></h3></center>
            </div>
        {% endif %}
        <center><p><h1>{{ post.titulo }}</h1></p></center>
        <center><img>{% cloudinary post.imagem %}</img></center>
        <center><p><h2>{{ post.apresentacao|linebreaksbr }}</h2></p></center>
    </div>
    <footer>
        <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="2"></div>
    </footer>
{% endblock %}